### ISSUE TITLE
작업 진행 상황 파악용 이슈

### ISSUE THREAD

**Issue by uinus-wongil** [ubittz/meetu-front-pc#97]
- [x] 로그인
- [x] 회원가입
- [x] 계정 찾기
- [x] 메인 화면
- [x] 모임 상세
- [x] 모임 더보기
- [x] 내모임
- [x] 모임 생성
- [x]  마이페이지
- [x] 결제
- [x] 내정보 수정
- [x] 결제 내역
- [x] 호스트 등록 신청
- [x] 프로필 팝업
- [x] 프로필 상세

**Comment by uinus-wongil** [comment]
@fire-irror 결제 시작

**Comment by uinus-wongil** [comment]
내정보 수정 작업 - 김원길

**Comment by shg-uinus** [comment]
호스트 등록 신청 - 성현관

**Comment by shg-uinus** [comment]
프로필 상세 - 성현관
